### ISSUE TITLE
2 columns make codes tigh

### ISSUE THREAD

**Issue by lushl9301** [algorhythms/Algo-Quicksheet#4]
For example

PDF release
Page 42.
left side of section: -> 15.3.4 Evaluate Pre-fix Expressions

I know it is unreasonable to show code in single column. That could look worse.

Maybe you wanna change the page size to another one instead of A4?

**Comment by idf** [comment]
thanks, fixed. 

removed inessential code. 

e0da43cf76c97a72988d11eafafab5042a144617

**Comment by lushl9301** [comment]
Dan Zong dai wo fei

How to get involved?

**Comment by idf** [comment]
Pull requests first. If commitments shown, surely add you as collaborator.
